---
title: "Clustering"
output:
  html_document:
    df_print: paged
---

```{r}
library(rio)
library(here)
library(tidyverse)
library(kohonen)
library(viridis)
library(agricolae)
library(corrplot)
source(here('./scripts/winsorize.R'))
```

```{r}
Transfermarkt <- import(here('./data/processed/Transfermarkt.xlsx'))
Finanzas <- import(here('./data/processed/Finanzas.xlsx'))

df <- inner_join(Finanzas, Transfermarkt, by = c("EQUIPO","AÑO")) %>%
  #filter(AÑO != 2020) %>%
  select(EQUIPO,
         PAIS,
         AÑO,
         MATERIAL, 
         INGRESOS,
         EBIT,
         ASISTENCIA,
         MV,
         MV5,
         FICHAJES,
         CAPACIDAD,
         OCUPACION,
         RANKNAC,
         RANKNAC5,
         WINPCT,
         WINPCT5)
```

# PCA
```{r}
# This will perform a PCA, with a possibility of rotation.
Extract_Factors <- function(data, rank, rotation = F) {
  
  PCA_Full <- prcomp(data, 
                scale. = T,
                rank. = rank) 
  
  print(summary(PCA_Full))
  scores <- as.array(scale(PCA_Full$x))
  
  if (rotation) {
    rotation <- varimax(PCA_Full$rotation)
    rot.scores <- as.array(scores %*% rotation$rotmat)
    
    factors <- rot.scores
    corrplot(cor(data,rot.scores))
    
  } else {
    factors <- scores
    corrplot(t(cor(data,scores)))
  }
  
  return(factors)
}

# This will tell us the variables that are mostly correlated to each new factor

studyFactors <- function(pca_data, factors) {
  
  correlations <- as.data.frame(cor(pca_data,factors))
  
  correlations$var <- row.names(correlations)
  
  for (i in 1:(ncol(correlations)-1)) {
    
    table <- correlations %>%
      mutate(color = correlations[[i]]>=0,
            abs = abs(correlations[[i]])) %>%
      top_n(n=10,wt=abs) %>%
      mutate(tag = 1:nrow(.)) %>% 
      ggplot() +
      geom_col(aes(x=reorder(var,abs),y=abs,fill=color)) +
      geom_hline(yintercept = 0.7, linetype = "dashed") +
      scale_fill_manual(name = "Correlation sign",
                        labels = c("Negative","Positive"),
                        values = c("Red","Blue")) +
      scale_y_continuous(limits = c(0,1)) +
      labs(x = "Original Variable",
           y = "Absolute Value of correlation") +
      coord_flip() +
      theme_bw()
     
    print(table)
      
  }
}

PCA_Analysis <- function(data, rank, rotation, cor = 0.7) {
  
  data <- data[,apply(data, 2, var, na.rm=TRUE) != 0]
  
  factors <- Extract_Factors(data, rank, rotation)
  #studyFactors(data, factors)
  
  return(factors)
}
```

```{r}
scores <- df %>%
  select_if(is.numeric) %>%
  select(-AÑO) %>%
  PCA_Analysis(rank = 6, rotation = T)
```
# SOM
```{r}
scores <- scores %>%
  as.data.frame() %>%
  mutate(across(everything(), winsorize, prob = 0.05)) %>%
  rename(ACTINGR = V1,
         RENDEP = V2,
         EBIT = V3,
         OCUPACION = V4,
         RANKNAC = V5,
         AFICION = V6)

trainingMatrix <- as.matrix(scores)

rownames(trainingMatrix) <- paste(df$EQUIPO,"|",df$AÑO)
```

```{r}
xdim = 15
ydim = 15
set.seed(9546)
som_grid <- somgrid(xdim = xdim, ydim = ydim, topo="hexagonal")
som_model <- som(trainingMatrix, 
                 grid = som_grid, 
                 rlen = 10000, 
                 alpha = 0.01, 
                 keep.data = TRUE)

plot(som_model, type="changes")
plot(som_model, type = "mapping")
```

```{r}
for (i in 1:ncol(trainingMatrix)) {
  plot(som_model, 
       type = "property", 
       property = getCodes(som_model)[,i], 
       main = colnames(getCodes(som_model))[i],
       palette.name = viridis_pal(option = "A",
                                  direction = -1,
                                  begin = 0.15,
                                  end = 1))
}
```

# Clustering Jerárquico
```{r}
tree <- hclust(object.distances(som_model , "codes"),
               method="ward.D2")

K <- 5
som_cluster <- cutree(tree, k=K)
neuron_cluster <- data.frame(neuron = 1:(xdim*ydim),
                             cluster = as.factor(som_cluster))

df <- df %>%
  mutate(neuron = som_model$unit.classif) %>%
  left_join(neuron_cluster)

scores <- scores %>%
  mutate(neuron = som_model$unit.classif) %>%
  left_join(neuron_cluster)

plot(som_model, 
     type = "mapping",
     bgcol = viridis(K)[som_cluster], 
     main = "Clusters")
```
# ANOVA
```{r}
ANOVA_ACTINGR <-aov(data = scores,  ACTINGR ~ cluster)
summary(ANOVA_ACTINGR)
TukeyHSD(ANOVA_ACTINGR)
scheffe.test(ANOVA_ACTINGR, "cluster", console = T)
```

```{r}
ANOVA_RENDEP <-aov(data = scores, RENDEP ~ cluster)
summary(ANOVA_RENDEP)
TukeyHSD(ANOVA_RENDEP)
scheffe.test(ANOVA_RENDEP, "cluster", console = T)
```

```{r}
ANOVA_EBIT <-aov(data = scores, EBIT ~ cluster)
summary(ANOVA_EBIT)
TukeyHSD(ANOVA_EBIT)
scheffe.test(ANOVA_EBIT, "cluster", console = T)
```

```{r}
ANOVA_OCUPACION <-aov(data = scores, OCUPACION ~ cluster)
summary(ANOVA_OCUPACION)
TukeyHSD(ANOVA_OCUPACION)
scheffe.test(ANOVA_OCUPACION, "cluster", console = T)
```

```{r}
ANOVA_RANKNAC <-aov(data = scores, RANKNAC ~ cluster)
summary(ANOVA_RANKNAC)
TukeyHSD(ANOVA_RANKNAC)
scheffe.test(ANOVA_RANKNAC, "cluster", console = T)
```

```{r}
ANOVA_AFICION <-aov(data = scores, AFICION ~ cluster)
summary(ANOVA_AFICION)
TukeyHSD(ANOVA_AFICION)
scheffe.test(ANOVA_AFICION, "cluster", console = T)
```

# Múltiplos de ingresos
```{r}
Deals <- import(here('./data/processed/M&A.xlsx')) %>%
  mutate(VALOR = VALOR*100/PART) %>%
  filter(!is.na(VALOR), !is.na(PART)) %>%
  select(EQUIPO, AÑO, VALOR, PART)

ratios <- df %>%
  left_join(Deals, by = c("EQUIPO","AÑO")) %>%
  mutate(RATIO_INGRESOS = VALOR/INGRESOS) %>%
  group_by(cluster) %>%
  summarise(RATIO_CLUSTER = mean(RATIO_INGRESOS, na.rm = T))

df %>%
  inner_join(ratios) %>%
  mutate(EV = round(INGRESOS*RATIO_CLUSTER,2)) %>%
  filter(AÑO == 2019) %>%
  arrange(desc(EV)) %>%
  mutate(TOP = row_number()) %>%
  select(`Nº` = TOP, 
         Equipo = EQUIPO, 
         Ingresos = INGRESOS, 
         `Ratio EV/Ingresos` = RATIO_CLUSTER,
         `Valor de empresa (€m)`=EV)
```

