---
title: "ORBIS"
output: html_notebook
---

# Carga de paquetes necesarios
```{r}
library(here)
library(readxl)
library(tidyverse)
library(lubridate)
```

# Carga y limpieza de los conjuntos de datos
## Activos
```{r}
activo <- read_xlsx(here("./data/raw/Assets.xlsx"))

activo[activo == "n.d."] <- NA

activo <- activo %>%
  rename(Equipo = `Nombre empresaAlfabeto latino`,
         `ID Equipo` = `Número de identificación BvD`,
         row = `...1`) 

cols_to_pivot <- setdiff(names(activo), c("Equipo", "ID Equipo","row", "Standardized country"))

activo <- activo %>%
  pivot_longer(cols = all_of(cols_to_pivot), names_to = "columna", values_to = "Valor") %>%
  mutate(
    Cuenta = gsub("\\s+EUR\\s+\\d+", "", columna),
    Año = as.numeric(gsub(".*\\b(\\d{4})\\b.*", "\\1", columna)),
    Valor = as.numeric(Valor)/1e6
  )  %>%
  select(-c(row,columna)) %>%
  pivot_wider(names_from = "Cuenta", values_from = "Valor") %>%
  select(BvD_ID = `ID Equipo`,
         AÑO = Año,
         MATERIAL = `Inmovilizado inmaterial`,
         INTANGIBLE = `Inmovilizado material`)  %>%
  filter(AÑO > 2014, AÑO < 2024)
```

## Pasivos
```{r}
pasivo <- read_xlsx(here("./data/raw/Liabilities.xlsx"))

pasivo[pasivo == "n.d."] <- NA

pasivo <- pasivo %>%
  rename(Equipo = `Nombre empresaAlfabeto latino`,
         `ID Equipo` = `Número de identificación BvD`,
         row = `...1`) 

cols_to_pivot <- setdiff(names(pasivo), c("Equipo", "ID Equipo","row", "Standardized country"))

pasivo <- pasivo %>%
  pivot_longer(cols = all_of(cols_to_pivot), names_to = "columna", values_to = "Valor") %>%
  mutate(
    Cuenta = gsub("\\s+EUR\\s+\\d+", "", columna),
    Año = as.numeric(gsub(".*\\b(\\d{4})\\b.*", "\\1", columna)),
    Valor = as.numeric(Valor)/1e6
  )  %>%
  select(-c(Equipo, row,columna)) %>%
  pivot_wider(names_from = "Cuenta", values_from = "Valor") %>%
  select(BvD_ID =`ID Equipo`,
         AÑO=Año,
        # Pasivos
        `Fondos de los accionistas`, 
        `Pasivos no corrientes`,
        `Deudas a corto plazo`,
        `Total pasivo`) %>%
  filter(AÑO > 2014, AÑO < 2024)
```

## PyG
```{r}
PyG <- read_xlsx(here("./data/raw/PyG.xlsx"))

PyG[PyG == "n.d."] <- NA

PyG <- PyG %>%
  rename(Equipo = `Nombre empresaAlfabeto latino`,
         `ID Equipo` = `Número de identificación BvD`,
         row = `...1`) 

cols_to_pivot <- setdiff(names(PyG), c("Equipo", "ID Equipo","row", "Standardized country"))

PyG <- PyG %>%
  pivot_longer(cols = all_of(cols_to_pivot), names_to = "columna", values_to = "Valor") %>%
  mutate(
    Cuenta = gsub("\\s+EUR\\s+\\d+", "", columna),
    Año = as.numeric(gsub(".*\\b(\\d{4})\\b.*", "\\1", columna)),
    Valor = as.numeric(Valor)/1e6
  )  %>%
  select(-c(Equipo, row,columna)) %>%
  pivot_wider(names_from = "Cuenta", values_from = "Valor") %>%
  select(BvD_ID =`ID Equipo`,
         AÑO = Año,
        # PyG
        INGRESOS = `Ingresos explotación (Cifra ventas)`, 
        EBIT=`P/G operacionales [=EBIT]`) %>%
  filter(AÑO > 2014, AÑO < 2024)
```

## Join de todo
```{r}
Equipos <- import(here('./data/aux/Equipos.xlsx'))

Finanzas <- activo %>%
  inner_join(PyG,
            by = c("BvD_ID", "AÑO")) %>%
  inner_join(Equipos, by = c("BvD_ID")) %>%
  select(-c(TRANSFERMARKT_HANDLE,TRANSFERMARKT_ID,BvD_ID)) %>%
  filter(complete.cases(.))

NOT_ORBIS <- import(here('./data/raw/other_accounts.xlsx')) %>%
  select(names(Finanzas))

Finanzas <- rbind(Finanzas,NOT_ORBIS) %>%
  distinct()
```

```{r, warning = F}
Deals <- import(here('./data/raw/Deals.xlsx')) %>%
  filter(!is.na(`Target BvD ID number`),
         !`Acquiror BvD ID number` %in% Equipos$BvD_ID) %>%
  left_join(Equipos, by = c("Target BvD ID number"="BvD_ID")) %>%
  select(EQUIPO,
         COMPRADOR = `Acquiror name`,
         TIPO_DEAL = `Deal type`,
         VALOR = `Deal value EUR`,
         PART = `Acquired stake (%)`,
         FECHA = `Last deal status date`) %>%
  mutate(VALOR = as.numeric(VALOR)/1e6,
         PART = as.numeric(PART),
         AÑO = year(FECHA),
         ID = 1:nrow(.)) %>%
  filter(!is.na(EQUIPO),
         between(AÑO, 2014, 2023),
         TIPO_DEAL != "Acquisition increased from 100% to 100%")

exchange_rates <- import(here('./data/aux/exchange_rates.xlsx'))

Deals %>%
  filter(is.na(VALOR)) %>%
  select(ID, EQUIPO, COMPRADOR, AÑO)

# Leeds 2023
# FUENTE: https://www.cityam.com/who-owns-leeds-united-how-much-did-the-49ers-group-pay-andrea-radrizzani-in-2023/
Deals$PART[Deals$ID == 6] <- 56
Deals$VALOR[Deals$ID == 6] <- 170*exchange_rates$rate[exchange_rates$Año == 2018]
Deals$COMPRADOR[Deals$ID == 6] <- "49ERS ENTERPRISES PTY LTD"

#Palermo 2016
#FUENTE: https://www.goal.com/en/news/man-city-owners-set-buy-italian-club-palermo-eur13m-takeover/bltd77f0ea0764de0f7
Deals$PART[Deals$ID == 16] <- 80
Deals$VALOR[Deals$ID == 16] <- 13

# Ascoli 2021
Deals$PART[Deals$ID == 19] <- 31
Deals$VALOR[Deals$ID == 19] <- 6.2
Deals$COMPRADOR[Deals$ID == 19] <- "NORTH SIXTH GROUP"

# Ipswich 2021
Deals$VALOR[Deals$ID == 25]  <- 40
# 2023	Bright Path Sports Partners	40%	Up to £105 million (IPSWICH)

# Toulouse 2020
Deals$VALOR[Deals$ID == 32]  <- 20

# Everton, 2016, Moshiri, 49,9%, GBP 200m

# Como, 2019, SENT ENTERTAINMENT
Deals$VALOR[Deals$ID == 40] <- 0.85

# Elche CF, 2019, SCORE CLUB 2019 SL
Deals$PART[Deals$ID == 36] <- 70
Deals$VALOR[Deals$ID == 36] <- 20

Deals$ID[grepl("unknown majority stake %",Deals$TIPO_DEAL, fixed=T)]

Deals$PART[Deals$ID %in% c(13,23)] <- 80

Deals$VALOR[Deals$ID == 7] <- 25
```

```{r}
export(Finanzas, here('./data/processed/Finanzas.xlsx'),rowNames = F)
export(Deals, here('./data/processed/M&A.xlsx'),rowNames = F)
```

