---
title: "Construcción de conjunto de datos"
author: "Carlos Eduardo Gómez-Torres"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Configuración global para todos los chunks
knitr::opts_chunk$set(results = 'hold',
                      message = FALSE, 
                      warning = FALSE)
```


# Carga de paquetes
```{r}
library(rio)
library(here)
library(tidyverse)
library(zoo)
library(viridis)

calculate_moving_average <- function(x) {
  rollapply(x, width = 5, FUN = mean, align = "right", fill = NA)
}
```

# Datos deportivos
```{r}
Transfers <- import(here('./data/raw/Transfers.xlsx'))
Ranking <- import(here('./data/raw/Ranking.xlsx'))
Attendance <- import(here('./data/raw/Attendance.xlsx'))
Stadium <- import(here('./data/raw/Stadiums.xlsx'))
seasons_years <- data.frame(YEAR = 2009:2023,
                            SEASON = c("09/10","10/11","11/12",
                                       "12/13","13/14","14/15","15/16",
                                       "16/17","17/18","18/19","19/20",
                                       "20/21","21/22","22/23","23/24"))

Teams <- import(here('./data/aux/Teams.xlsx'))

Transfermarkt <- Attendance %>%
  inner_join(seasons_years, by = "SEASON") %>%
  inner_join(Transfers, by = c("TRANSFERMARKT_HANDLE","YEAR")) %>%
  inner_join(Stadium, by = "TRANSFERMARKT_HANDLE") %>%
  inner_join(Teams %>% select("TRANSFERMARKT_HANDLE","TRANSFERMARKT_ID","COUNTRY"), 
             by = "TRANSFERMARKT_HANDLE") %>%
  left_join(Ranking, by = c("TRANSFERMARKT_HANDLE","YEAR","COUNTRY")) %>%
  filter(YEAR < END, YEAR >= CONSTRUCTED)


Transfermarkt <- Transfermarkt %>%
  mutate(CAPACITY = case_when(
    TEAM == "Chelsea" & between(YEAR, 2013, 2017) ~ 41798, 
    TEAM == "Clermont Foot" & YEAR >= 2018 ~ 13000,
    TEAM == "Düsseldorf" ~ 54600,  # Se corrigió la sintaxis aquí
    TEAM == "Manchester United" & between(YEAR, 2013, 2017) ~ 75643, 
    TEAM == "Tottenham Hotspur" & between(YEAR, 2013, 2018) ~ 90000,
    TEAM == "CD Eldense" & YEAR == 2023 ~ 5776 ,
    TRUE ~ CAPACITY
  ))
```

```{r}
Transfermarkt <- Transfermarkt %>%
  mutate(WINPCT = W / (W + D + L),
         OCCUPANCY = ATTENDANCE / CAPACITY,
         ANTEST = 2024 - CONSTRUCTED)

Transfermarkt <- Transfermarkt %>%
  group_by(TEAM) %>%
  arrange(YEAR) %>%
  mutate(WINPCT5 = calculate_moving_average(WINPCT),
         MV5  = calculate_moving_average(MV),
         NET_TRANSFERS5 = calculate_moving_average(NET_TRANSFERS),
         RANKNAC5 = calculate_moving_average(RANKNAC)) %>%
  ungroup() %>%
  filter(complete.cases(.))
```

```{r}
Transfermarkt %>%
  mutate(DIVISION = as.factor(DIVISION)) %>%
  ggplot() +
  geom_point(aes(x = WINPCT,y = RANKNAC, color = DIVISION)) +
  scale_color_viridis(discrete = T,
                      name = "División",
                      labels = c("Primera","Segunda","Tercera")) +
  facet_wrap(~COUNTRY) +
  geom_hline(yintercept = c(72,35), linetype = "dashed") +
  labs(x = "Win %",
       y = "Rank") +
  theme_bw()


Transfermarkt %>%
  mutate(DIVISION = as.factor(DIVISION)) %>%
  ggplot() +
  geom_point(aes(x = RANKNAC,y = RANKNAC5, color = DIVISION)) +
  scale_color_viridis(discrete = T,
                      name = "División",
                      labels = c("Primera","Segunda","Tercera")) +
  facet_wrap(~COUNTRY) +
  labs(x = "Rank",
       y = "Rank (last 5 yrs)") +
  theme_bw()

Transfermarkt %>%
  mutate(DIVISION = as.factor(DIVISION)) %>%
  ggplot() +
  geom_point(aes(x = MV,y = RANKNAC, color = DIVISION)) +
  scale_color_viridis(discrete = T,
                      name = "División",
                      labels = c("Primera","Segunda","Tercera")) +
  scale_x_log10() +
  facet_wrap(~COUNTRY) +
  theme_bw()
```


```{r}
Transfermarkt <- Transfermarkt %>%
  select(-c(W,
            D,L,PTS,COUNTRY,END,DIVISION,POS,TRANSFERMARKT_ID,
            TRANSFERMARKT_HANDLE,SEASON,CONSTRUCTED)) %>%
  filter(complete.cases(.))


export(Transfermarkt, here('./data/processed/Transfermarkt.xlsx'), rowNames = F)
```

